// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vsjmahcbikloqckiubvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzam1haGNiaWtsb3Fja2l1YnZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NzY0ODUsImV4cCI6MjA2NzA1MjQ4NX0.Gv_k9ZNww-Cd1RD96a3105quoTQCCEE5RUS6zEjrNjM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});